/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package janelas;

/**
 *
 * @author ASUS
 */
public class janelainf extends javax.swing.JInternalFrame {

    /**
     * Creates new form janelainf
     */
    public janelainf() {
        initComponents();
        displaySystemInformation();
    }
private String getSystemInformation() {
        // Colete informações do sistema
        String os = System.getProperty("os.name");
        String osVersion = System.getProperty("os.version");
        String javaVersion = System.getProperty("java.version");
        String userName = System.getProperty("user.name");
        String userHome = System.getProperty("user.home");

        // Construa uma string com as informações coletadas
        StringBuilder info = new StringBuilder();
        info.append("Sistema Operativo: ").append(os).append("\n");
        info.append("Versão do SO: ").append(osVersion).append("\n");
        info.append("Versão do Java: ").append(javaVersion).append("\n");
        info.append("Utilizador: ").append(userName).append("\n");
        info.append("Home do Utilizador: ").append(userHome).append("\n");

        return info.toString();
    }

    private void displaySystemInformation() {
        String systemInfo = getSystemInformation();
        jTextPane1.setText(systemInfo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setClosable(true);

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
