/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package janelas;
import java.sql.*;
import conexao.MyConnection;
import java.io.IOException;
//Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class JanelaConsQuartos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaConsQuartos
     */
    public JanelaConsQuartos() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
        new Object[][] {},
        new String[] {"Numero", "Disponivel", "Hospede ID", "Hospede Nome"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    Tabela.setModel(model);
    
    carregarTodosQuartos();
    }
    //Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *///Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setClosable(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        jLabel13.setText("Procurar por Numero:");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Ver Todos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Disponivel", "Hospede ID", "Hospede Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(btnProcurar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcurar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
//Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
//Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        btnProcurar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String nomePesquisa = txtPesquisa.getText();
                pesquisarQuarto(nomePesquisa);
            }
        });}
    private void carregarTodosQuartos() {
    String sql = "SELECT q.numero, q.disponivel, q.hospede, h.nome FROM quartos q LEFT JOIN hospedes h ON q.hospede = h.id";
    MyConnection myconn = new MyConnection();
    try (Connection conn = myconn.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            int numero = rs.getInt("numero");
            boolean disponivel = rs.getBoolean("disponivel");                                                                   //Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
            int hospede_id = rs.getInt("hospede");
            String nome = rs.getString("nome");
            
            model.addRow(new Object[]{
                numero,
                disponivel,
                hospede_id == 0 ? "" : hospede_id,
                nome == null ? "" : nome
            });
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao carregar quartos: " + ex.getMessage());
    }
}
        private void pesquisarQuarto(String numero) {
    String sql = "SELECT q.numero, q.disponivel, q.hospede, h.nome FROM quartos q LEFT JOIN hospedes h ON q.hospede = h.id WHERE q.numero = ?";
    MyConnection myconn = new MyConnection();
    try (Connection conn = myconn.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, Integer.parseInt(numero));
        ResultSet rs = pstmt.executeQuery();

        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        model.setRowCount(0);

        if (rs.next()) {
            int quarto_numero = rs.getInt("numero");
            boolean disponivel = rs.getBoolean("disponivel");
            int hospede_id = rs.getInt("hospede");
            String nome = rs.getString("nome");

            model.addRow(new Object[]{
                quarto_numero,
                disponivel,
                hospede_id == 0 ? "" : hospede_id,
                nome == null ? "" : nome
            });
        } else {
            JOptionPane.showMessageDialog(this, "Quarto não encontrado.");
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao pesquisar quarto: " + ex.getMessage());
    }

        //Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        carregarTodosQuartos();
    }//GEN-LAST:event_btnLimparActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;                                                     //Projeto Desenvolvido por Guilherme Martins e Hugo Oliveira
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
